name: cg-iaa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.13.0
  - torchvision>=0.14.0
  - cudatoolkit=11.8  # Adjust based on your CUDA version
  - pip
  - pip:
    - transformers>=4.25.0
    - Pillow>=9.0.0
    - timm>=0.6.0
    - numpy>=1.20.0
    - tqdm>=4.60.0
    - ftfy>=6.0.0
    - regex>=2022.0.0
    - matplotlib>=3.5.0
    - requests>=2.25.0

